### ISSUE TITLE
id: inspections and id: future inspections

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-SanitaryCode#21]
I think these two pages should like back to the intro page.

`id: inspections` should say something like 'you told us you had already had an inspection. What was the name of the code enforcement agency?'

`id: future inspections` should say 'You told us you had booked an inspection with an official from a code enforcement agency' and then have the place for name of agency and date of future inspection. Reason I say this is because you don't want to be kicking people out this far along.

**Comment by mikecronin7** [comment]
Updated these screens
